apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foobar
  name: foobar
  # this should not be possible when setting up proper service accounts
  namespace: tenant-a-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foobar
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}